124 deploying new chatbot app to docker compose
Meng-V/smartchatbot pull request #125
Opened 2024-04-20 22:21 UTC by TranHVLoc

#124
Add docker files including images for: Frontend and Backend
(+1) hot fix for React code with `messageId`

2024-04-22 16:43 UTC, dominhnhut01 requested changes

2024-04-22 16:43 UTC, dominhnhut01 commented on new-chatbot-app/backend.dockerfile
> +CMD npx prisma migrate dev --preview-feature && npm run start
Please change this to npm run build and serve the code in production mode

2024-04-22 16:43 UTC, dominhnhut01 commented on new-chatbot-app/client/frontend.dockerfile
> +CMD ["npm", "start", "--", "--host"]
Change this to npm run build and serve the code in production mode

2024-04-26 10:55 UTC, dominhnhut01 approved these changes
Tested and run

2024-04-26 15:15 UTC, Lamp-Nguyen approved these changes

2024-04-27 20:22 UTC, merged